before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-xetex
- chmod u+x ./travis/build.sh
- chmod u+x ./travis/publish.sh

script: "./travis/build.sh"

after_success:
- "./travis/publish.sh"

env:
  global:
  # do: travis encrypt GH_OAUTH_TOKEN=<githubtoken> --add
  - secure: dw8ufvNHyfG+vI4IaaKIpYMUikNb+3n3oQPp8I/pkJUhoVCj6DbvV93vtFP0OkTG/ZyZkOf7MCitC3Uj6M/octUI3jPOYF/hsC9NR2l0agDBCq/gDtHDZqksIyHEySv6TmI9TAnzUch5Fa9RMzB1U0WIlAkwDKEV5rNTDj/hLGq1UGN6HsFaIxRSXFRKbgqHoyG/OdcDBM4GgJ/qH4bJ8P8k5FvPmaH5MHNtizrPBykuZFLNzuAWuhm8eVZKua19psLPAth11V34llngVS03c8XraK9byXp3OsuHsPxmDmzcfoDLXZ2oNet++cjCXrMnb0vKARvkggU1/oZYS2VC0c5B6PJ8hHK98bJvWaCrIM+RUYF7CrwsQvaluijZKhxatuLDTSkJhVQoOpF/MLcnISY/aA9Hd//mvr4KVoqxioV8upapmjayUPJ9TZPPspk4tPpnfQZG4jtS0FUt7Jfnx4UScm+kh6T3Vd+lNZsBOJe8L/e/R71INYpnVB9yOw1UK/JsncFOT9QqFEIMh+pjYqk8qpGPfdiU2Tbs4S9FxijISNNz7aKX3Xn4vNPmhmC3+WFntyTzgAYpbpIbpeiJkbWmnqpJQ2VPod4Zu2OLTMXzCfWPqV/pznU/ycsbsFk3tONk5dLwXu3srn5TF8b6pOjSCj9jyqstmS7yGDtZ7hQ=
  - GH_USER_NAME: VaudoiseAssurances
  - GH_PROJECT_NAME: API-Guidelines
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - RESULT_PDF_PATH=$TRAVIS_BUILD_DIR/api-guidelines.pdf
  - TZ="Europe/Zurich"
