before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-xetex
- chmod u+x ./travis/build.sh
- chmod u+x ./travis/publish.sh

script: "./travis/build.sh"

after_success:
- "./travis/publish.sh"

env:
  global:
  # do: travis encrypt GH_OAUTH_TOKEN=<githubtoken> --add
  - secure: MLcJR6q+Lky7GrEmoDFuw+G2KvRKhOBE5j05Os+EhwACp4O9LVyW9WxuMY21FiBcMxqjDjSNOo6kCBpzMZ7NypMb4c5+WeJR2iYRRsot/+fbuVBeTIgXtfrFQ0CmyRHd13XL+VCjWTlnq4Vy4kwhiuhlhlo/0Br4BbhbLExaYngvs6VL0wZJOBqj5vQADDb2pJJmVfm2quOETO8vyjIoCT5F9Yf+G1oLasje9ebuuBFm5hiN4aNjOWbZtOX7mQq5SW1N1avLBltE3NRy/4XeinpUIFKv+zBI7IiJ6P4tRxrcVzarbL1KZZbLLPqblJUhIGB+Yt062lLh9KHgjTwiBMBsM4l/J2K+MNsjzBApc9oqhwnm3RLMrHk22mDnoO5me0D5waWNb9iCkn+syTSORxVtl4dfVc4UJnTYLlw4txpcTdH+Hkia5c7pFPdgaiCUCl1lMii7mviKmwIqE8kSQ2/w4oiekX8PbnhGmQzDHkzOzdACO+Td1NRKEsMVlO9dOCzDWouHA9ErL0Meogq3KglJGQkBhpTdRr9NxLjWrdDsB/ats2yPziSnjEYrVbg9GdPeLRpM8MkinYqRfTEdRx2Ch7xi/S6byMiipzHpAVMHMunoO9OlTdA1VJNAR28lbjC/FxI27zGJAOaPcCDndvrWo0ItouQ7SKSvEtdRt5U=
  - GH_USER_NAME: VaudoiseAssurances
  - GH_PROJECT_NAME: API-Guidelines
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - RESULT_PDF_PATH=$TRAVIS_BUILD_DIR/api-guidelines.pdf
  - TZ="Europe/Zurich"
